//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference2
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientConfirmRequestData", Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference2.ClientConfirmWithAmountRequestData))]
    public partial class ClientConfirmRequestData : object
    {
        
        private string LoginAccountField;
        
        private long TokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LoginAccount
        {
            get
            {
                return this.LoginAccountField;
            }
            set
            {
                this.LoginAccountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Token
        {
            get
            {
                return this.TokenField;
            }
            set
            {
                this.TokenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientConfirmWithAmountRequestData", Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService")]
    public partial class ClientConfirmWithAmountRequestData : ServiceReference2.ClientConfirmRequestData
    {
        
        private long OrderIdField;
        
        private long AmountField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long OrderId
        {
            get
            {
                return this.OrderIdField;
            }
            set
            {
                this.OrderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public long Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientConfirmResponseData", Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference2.ClientConfirmResponseDataAddData))]
    public partial class ClientConfirmResponseData : object
    {
        
        private short StatusField;
        
        private string CardNumberMaskedField;
        
        private long RRNField;
        
        private long TokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CardNumberMasked
        {
            get
            {
                return this.CardNumberMaskedField;
            }
            set
            {
                this.CardNumberMaskedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public long RRN
        {
            get
            {
                return this.RRNField;
            }
            set
            {
                this.RRNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public long Token
        {
            get
            {
                return this.TokenField;
            }
            set
            {
                this.TokenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientConfirmResponseDataAddData", Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService")]
    public partial class ClientConfirmResponseDataAddData : ServiceReference2.ClientConfirmResponseData
    {
        
        private string AddDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AddData
        {
            get
            {
                return this.AddDataField;
            }
            set
            {
                this.AddDataField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService", ConfigurationName="ServiceReference2.ConfirmServiceSoap")]
    public interface ConfirmServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService/ConfirmPayment", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference2.ConfirmPaymentResponse> ConfirmPaymentAsync(ServiceReference2.ConfirmPaymentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService/ConfirmPaymentWithA" +
            "ddData", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference2.ConfirmPaymentWithAddDataResponse> ConfirmPaymentWithAddDataAsync(ServiceReference2.ConfirmPaymentWithAddDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService/ConfirmPaymentWithA" +
            "mount", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference2.ConfirmPaymentWithAmountResponse> ConfirmPaymentWithAmountAsync(ServiceReference2.ConfirmPaymentWithAmountRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmPaymentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmPayment", Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService", Order=0)]
        public ServiceReference2.ConfirmPaymentRequestBody Body;
        
        public ConfirmPaymentRequest()
        {
        }
        
        public ConfirmPaymentRequest(ServiceReference2.ConfirmPaymentRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService")]
    public partial class ConfirmPaymentRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference2.ClientConfirmRequestData requestData;
        
        public ConfirmPaymentRequestBody()
        {
        }
        
        public ConfirmPaymentRequestBody(ServiceReference2.ClientConfirmRequestData requestData)
        {
            this.requestData = requestData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmPaymentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmPaymentResponse", Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService", Order=0)]
        public ServiceReference2.ConfirmPaymentResponseBody Body;
        
        public ConfirmPaymentResponse()
        {
        }
        
        public ConfirmPaymentResponse(ServiceReference2.ConfirmPaymentResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService")]
    public partial class ConfirmPaymentResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference2.ClientConfirmResponseData ConfirmPaymentResult;
        
        public ConfirmPaymentResponseBody()
        {
        }
        
        public ConfirmPaymentResponseBody(ServiceReference2.ClientConfirmResponseData ConfirmPaymentResult)
        {
            this.ConfirmPaymentResult = ConfirmPaymentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmPaymentWithAddDataRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmPaymentWithAddData", Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService", Order=0)]
        public ServiceReference2.ConfirmPaymentWithAddDataRequestBody Body;
        
        public ConfirmPaymentWithAddDataRequest()
        {
        }
        
        public ConfirmPaymentWithAddDataRequest(ServiceReference2.ConfirmPaymentWithAddDataRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService")]
    public partial class ConfirmPaymentWithAddDataRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference2.ClientConfirmRequestData requestData;
        
        public ConfirmPaymentWithAddDataRequestBody()
        {
        }
        
        public ConfirmPaymentWithAddDataRequestBody(ServiceReference2.ClientConfirmRequestData requestData)
        {
            this.requestData = requestData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmPaymentWithAddDataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmPaymentWithAddDataResponse", Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService", Order=0)]
        public ServiceReference2.ConfirmPaymentWithAddDataResponseBody Body;
        
        public ConfirmPaymentWithAddDataResponse()
        {
        }
        
        public ConfirmPaymentWithAddDataResponse(ServiceReference2.ConfirmPaymentWithAddDataResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService")]
    public partial class ConfirmPaymentWithAddDataResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference2.ClientConfirmResponseDataAddData ConfirmPaymentWithAddDataResult;
        
        public ConfirmPaymentWithAddDataResponseBody()
        {
        }
        
        public ConfirmPaymentWithAddDataResponseBody(ServiceReference2.ClientConfirmResponseDataAddData ConfirmPaymentWithAddDataResult)
        {
            this.ConfirmPaymentWithAddDataResult = ConfirmPaymentWithAddDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmPaymentWithAmountRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmPaymentWithAmount", Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService", Order=0)]
        public ServiceReference2.ConfirmPaymentWithAmountRequestBody Body;
        
        public ConfirmPaymentWithAmountRequest()
        {
        }
        
        public ConfirmPaymentWithAmountRequest(ServiceReference2.ConfirmPaymentWithAmountRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService")]
    public partial class ConfirmPaymentWithAmountRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference2.ClientConfirmWithAmountRequestData requestData;
        
        public ConfirmPaymentWithAmountRequestBody()
        {
        }
        
        public ConfirmPaymentWithAmountRequestBody(ServiceReference2.ClientConfirmWithAmountRequestData requestData)
        {
            this.requestData = requestData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmPaymentWithAmountResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmPaymentWithAmountResponse", Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService", Order=0)]
        public ServiceReference2.ConfirmPaymentWithAmountResponseBody Body;
        
        public ConfirmPaymentWithAmountResponse()
        {
        }
        
        public ConfirmPaymentWithAmountResponse(ServiceReference2.ConfirmPaymentWithAmountResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService")]
    public partial class ConfirmPaymentWithAmountResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference2.ClientConfirmResponseData ConfirmPaymentWithAmountResult;
        
        public ConfirmPaymentWithAmountResponseBody()
        {
        }
        
        public ConfirmPaymentWithAmountResponseBody(ServiceReference2.ClientConfirmResponseData ConfirmPaymentWithAmountResult)
        {
            this.ConfirmPaymentWithAmountResult = ConfirmPaymentWithAmountResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface ConfirmServiceSoapChannel : ServiceReference2.ConfirmServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ConfirmServiceSoapClient : System.ServiceModel.ClientBase<ServiceReference2.ConfirmServiceSoap>, ServiceReference2.ConfirmServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ConfirmServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ConfirmServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), ConfirmServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConfirmServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ConfirmServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConfirmServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ConfirmServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConfirmServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference2.ConfirmPaymentResponse> ServiceReference2.ConfirmServiceSoap.ConfirmPaymentAsync(ServiceReference2.ConfirmPaymentRequest request)
        {
            return base.Channel.ConfirmPaymentAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.ConfirmPaymentResponse> ConfirmPaymentAsync(ServiceReference2.ClientConfirmRequestData requestData)
        {
            ServiceReference2.ConfirmPaymentRequest inValue = new ServiceReference2.ConfirmPaymentRequest();
            inValue.Body = new ServiceReference2.ConfirmPaymentRequestBody();
            inValue.Body.requestData = requestData;
            return ((ServiceReference2.ConfirmServiceSoap)(this)).ConfirmPaymentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference2.ConfirmPaymentWithAddDataResponse> ServiceReference2.ConfirmServiceSoap.ConfirmPaymentWithAddDataAsync(ServiceReference2.ConfirmPaymentWithAddDataRequest request)
        {
            return base.Channel.ConfirmPaymentWithAddDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.ConfirmPaymentWithAddDataResponse> ConfirmPaymentWithAddDataAsync(ServiceReference2.ClientConfirmRequestData requestData)
        {
            ServiceReference2.ConfirmPaymentWithAddDataRequest inValue = new ServiceReference2.ConfirmPaymentWithAddDataRequest();
            inValue.Body = new ServiceReference2.ConfirmPaymentWithAddDataRequestBody();
            inValue.Body.requestData = requestData;
            return ((ServiceReference2.ConfirmServiceSoap)(this)).ConfirmPaymentWithAddDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference2.ConfirmPaymentWithAmountResponse> ServiceReference2.ConfirmServiceSoap.ConfirmPaymentWithAmountAsync(ServiceReference2.ConfirmPaymentWithAmountRequest request)
        {
            return base.Channel.ConfirmPaymentWithAmountAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.ConfirmPaymentWithAmountResponse> ConfirmPaymentWithAmountAsync(ServiceReference2.ClientConfirmWithAmountRequestData requestData)
        {
            ServiceReference2.ConfirmPaymentWithAmountRequest inValue = new ServiceReference2.ConfirmPaymentWithAmountRequest();
            inValue.Body = new ServiceReference2.ConfirmPaymentWithAmountRequestBody();
            inValue.Body.requestData = requestData;
            return ((ServiceReference2.ConfirmServiceSoap)(this)).ConfirmPaymentWithAmountAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ConfirmServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ConfirmServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ConfirmServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://pec.shaparak.ir/NewIPGServices/Confirm/ConfirmService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ConfirmServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://pec.shaparak.ir/NewIPGServices/Confirm/ConfirmService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ConfirmServiceSoap,
            
            ConfirmServiceSoap12,
        }
    }
}
